### ISSUE TITLE
Problème navigation

### ISSUE THREAD

**Issue by Giulia59** [SocialGouv/maraudes-app#7]
**Scénario pour reproduire le problème**

- Je suis dans les demandes d'aide. 
- Je clique sur "demande de passeport" et j'arrive sur le détail de la demande "demande de passeport"
- Je clique sur personnes
- Je clique sur "Giulia"
- Je re-clique sur les demandes d'aides, je tombe sur le détail de la dernière demande d'aide consultée (demande de passeport)

**Problème**
Je tombe sur le détail de la dernière demande d'aide consultée (demande de passeport) alors que je voudrais tomber sur la liste des demandes d'aide.

C'est ce que j'avais en tête, mais totalement ok pour en discuter :)

**Comment by revolunet** [comment]
Hello, si j'ai bien compris, le problème doit être réglé, tu peux verifier stp ?

**Comment by revolunet** [comment]
resolved
